version: '3.8'

services:
  mariadb-invoices:
    image: mariadb:latest
    container_name: mariadb-invoices
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: streamflow_facturacion
      MARIADB_USER: admin
      MARIADB_PASSWORD: root
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"

  invoices-service:
    build: .
    container_name: invoices-service
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb-invoices
      - rabbitmq
    ports:
      - "50052:50052"
